// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeh2a9GkU8CMbbBQxxyEbV6cBp06U8cHY',
    appId: '1:278774091147:web:a7f56824b67d6f33a7738e',
    messagingSenderId: '278774091147',
    projectId: 'bovinapp-project',
    authDomain: 'bovinapp-project.firebaseapp.com',
    storageBucket: 'bovinapp-project.appspot.com',
    measurementId: 'G-YCFK1W3D81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgy1TYz4tVviJcigytTZsMVnWz1ftCT-4',
    appId: '1:278774091147:android:01071fc5c2b2ddeaa7738e',
    messagingSenderId: '278774091147',
    projectId: 'bovinapp-project',
    storageBucket: 'bovinapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTGmQWBMbqPSSnsZ4141R57wfMZs1ebLE',
    appId: '1:278774091147:ios:54af9674ca26f46aa7738e',
    messagingSenderId: '278774091147',
    projectId: 'bovinapp-project',
    storageBucket: 'bovinapp-project.appspot.com',
    iosClientId: '278774091147-9fj7eg59nv67g79ua8cactksoqvv6q8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bovinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTGmQWBMbqPSSnsZ4141R57wfMZs1ebLE',
    appId: '1:278774091147:ios:54af9674ca26f46aa7738e',
    messagingSenderId: '278774091147',
    projectId: 'bovinapp-project',
    storageBucket: 'bovinapp-project.appspot.com',
    iosClientId: '278774091147-9fj7eg59nv67g79ua8cactksoqvv6q8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bovinapp',
  );
}
